// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_EJmqWU_2a78BuhIgXexNvVOiPXLTNls',
    appId: '1:864173995067:web:eb2ada59780904f914d81e',
    messagingSenderId: '864173995067',
    projectId: 'recuperacioninterfaces',
    authDomain: 'recuperacioninterfaces.firebaseapp.com',
    storageBucket: 'recuperacioninterfaces.appspot.com',
    measurementId: 'G-9Q12X5LH6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrFziI76F5xOh11kVMVXpbyu2SyczF49w',
    appId: '1:864173995067:android:664c50674a6e5e7f14d81e',
    messagingSenderId: '864173995067',
    projectId: 'recuperacioninterfaces',
    storageBucket: 'recuperacioninterfaces.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDybYG9vsoPkhMSK7TAHZpZAIeA3h0u2jM',
    appId: '1:864173995067:ios:780f479d8030c6c414d81e',
    messagingSenderId: '864173995067',
    projectId: 'recuperacioninterfaces',
    storageBucket: 'recuperacioninterfaces.appspot.com',
    iosClientId: '864173995067-de01sgndk32jhuemd520bvcqfqu0l9av.apps.googleusercontent.com',
    iosBundleId: 'com.example.recuperacionInterfaces',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDybYG9vsoPkhMSK7TAHZpZAIeA3h0u2jM',
    appId: '1:864173995067:ios:780f479d8030c6c414d81e',
    messagingSenderId: '864173995067',
    projectId: 'recuperacioninterfaces',
    storageBucket: 'recuperacioninterfaces.appspot.com',
    iosClientId: '864173995067-de01sgndk32jhuemd520bvcqfqu0l9av.apps.googleusercontent.com',
    iosBundleId: 'com.example.recuperacionInterfaces',
  );
}
